---
title: "Plotly"
output: 
  html_document:
    toc: true
    toc_float: true
---


We're going to make some plotly plots.

```{r}
library(tidyverse)
library(p8105.datasets)
library(plotly)
```



```{r}
data("rest_inspec")

```




```{r}
data("rest_inspec")

nyc_inspections_italian = 
  rest_inspec %>% 
  drop_na() %>% 
  filter(cuisine_description == "Italian")

nyc_inspections_italian
```



```{r}
# Plotly line graph: This scatter plot shows the mean score of Italian restaurants in 2017 by month and Borough.
nyc_inspections_italian %>%
  separate(inspection_date, c("year", "month", "date")) %>% 
  filter(year == 2017) %>% 
  group_by(boro, month) %>% 
  summarise(mean_score = mean(as.numeric(score))) %>% 
  plot_ly(
    x = ~month, y = ~mean_score, type = "scatter", mode = "lines",
    color = ~boro, alpha = 1)

```


```{r}
# Plotly barchart: This barchart shows the number of Italian restaurant with Grade A in different Borough in 2017.
nyc_inspections_italian %>% 
  separate(inspection_date, c("year", "month", "date")) %>%
  filter(grade == "A", year == 2017) %>% 
  count(boro) %>% 
  mutate(boro = fct_reorder(boro, n)) %>% 
  plot_ly(x = ~boro, y = ~n, color = ~boro, type = "bar", colors = "viridis")
```


```{r}
# Plotly boxplot: This boxplot displays the scores in each Borough in 2017. The higher the score, the more severe of the violations.
nyc_inspections_italian %>% 
  separate(inspection_date, c("year", "month", "date")) %>%
  filter(year == 2017) %>% 
  mutate(score = as.numeric(score),
    boro = fct_reorder(boro, score)) %>% 
  plot_ly(y = ~score, color = ~boro, type = "box", colors = "viridis")
```

## Create a dashboard ...

Not here though.